name : Test CI/CD

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


    -uses: actions/checkout@v4

    -name: Install dependencies
     run:  npm install


    -name: Install TypeScript
     run: npm install -g typescript


    -name: Run test
     run: npm run test